substitutions:
  name: smablue-inverter
  friendly_name: SMA Wechselrichter

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: git
      url: https://github.com/Finest/esphome_sma_inverter
    components: [smabluetooth_solar]

sensor:
  - platform: smabluetooth_solar
    update_interval: 60s
    sma_inverter_bluetooth_mac: "00:80:25:09:4A:25"
    sma_inverter_password: "0000"
    sma_inverter_delay_values: 800ms

    inverter_status: 
      name: "Inverter Status"

    grid_relay: 
      name: "Grid relay Status"

    phase_a:
      voltage:
          name: "Voltage Phase A"
      current:
          name: "Current Phase A"
      active_power:
          name: "Power Phase A"
    phase_b:
      voltage:
          name: "Voltage Phase B"
      current:
          name: "Current Phase B"
      active_power:
          name: "Power Phase B"
    phase_c:
      voltage:
          name: "Voltage Phase C"
      current:
          name: "Current Phase C"
      active_power:
          name: "Power Phase C"

    pv1:
      voltage:
          name: "Voltage mppt1"
      current:
          name: "Current mppt1"
      active_power:
          name: "Power mppt1"

    pv2:
      voltage:
          name: "Voltage mppt2"
      current:
          name: "Current mppt2"
      active_power:
          name: "Power mppt2"

    frequency:
      name: "Frequency"

    energy_production_day:
      name: "Today's Generation"

    total_energy_production:
      name: "Total Energy Production"

    inverter_module_temp:
      name: "Inverter Module Temp"

    software_version:
      name: "Software Version"

    wakeup_time:
      name: "Wakeup Time"

    device_type:
      name: "Device Type"

    device_class:
      name: "Device Class"

    sma_inverter_bluetooth_signal_strength:
      name: "Inverter Bluetooth Signal Strength"